export default {
  login: "SDUBEY23",
  id: 74826047,
  node_id: "MDQ6VXNlcjc0ODI2MDQ3",
  avatar_url: "https://avatars.githubusercontent.com/u/74826047?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/SDUBEY23",
  html_url: "https://github.com/SDUBEY23",
  followers_url: "https://api.github.com/users/SDUBEY23/followers",
  following_url: "https://api.github.com/users/SDUBEY23/following{/other_user}",
  gists_url: "https://api.github.com/users/SDUBEY23/gists{/gist_id}",
  starred_url: "https://api.github.com/users/SDUBEY23/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/SDUBEY23/subscriptions",
  organizations_url: "https://api.github.com/users/SDUBEY23/orgs",
  repos_url: "https://api.github.com/users/SDUBEY23/repos",
  events_url: "https://api.github.com/users/SDUBEY23/events{/privacy}",
  received_events_url: "https://api.github.com/users/SDUBEY23/received_events",
  type: "User",
  site_admin: false,
  name: "Swapnil Dubey",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "I am Web Developer and have committed some of my projects here.",
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-11-21T14:41:13Z",
  updated_at: "2021-04-03T19:23:10Z"
  }